### ISSUE TITLE
Abort pending request to server?

### ISSUE THREAD

**Issue by linkurzweg** [DigitalBrainJS/safe-jsonp#1]
Hello, I'm using safe-jsonp in my React app and it's working fine, but I have one problem:
When aborting manually or when the timeout is reached, the request to the server itself keeps pending until the browser decides to cancel it after a long time. I am polling for data every few seconds, so the pending requests keep piling up, but there should only be one open connection at a time. Is there any way to completely abort a request?

**Comment by DigitalBrainJS** [comment]
Hello! Unfortunately, there are no JSONP libraries that could completely interrupt the pending request. Since each JSONP library uses a script element as a transport wich does not support any abort or timeout methods, there is no practical way to cancel a request at the http level. This is a well-known limitation of the browser DOM. You can read more about this issue here: 

- https://stackoverflow.com/questions/6472509/abort-jsonp-ajax-request-with-jquery
- https://stackoverflow.com/questions/5506425/how-to-set-a-timeout-for-loading-a-external-javascript-file-which-is-down
- https://maxchadwick.xyz/blog/script-tag-timeout-attribute

So, if possible, you should use ajax (xmlhttprequest / fetch) instead with Access-Control-Allow-Origin: * header from server side, because this technology fully supports the abort method at all levels.

**Comment by linkurzweg** [comment]
Hello! I was afraid that this might be the case but couldn't really find the information I needed. for now I am limited to JSONP unfortunately... Anyway, thank you very much for clearing that up and explaining it in detail :)

**Comment by DigitalBrainJS** [comment]
I have made some research & testing so it seems i have found some experimental solution wich is made possible by the availability of a sandbox mode in my package, classic JSONP packages can't provide this. So, I have updated the package to 0.5.0 and added ability to abort related http request. This feature will work only when:

- "abortable" option is set
- sandbox mode is activated and supported by a browser (except all IE, I hope you don't need them)
![jsonp](https://user-images.githubusercontent.com/12586868/63884161-5a837c80-c9de-11e9-9f22-35d3548b4f27.png)
Have fun :)

**Comment by linkurzweg** [comment]
Wow, that's really cool! I will try it out as soon as I can! Thank you very much!! :)

**Comment by linkurzweg** [comment]
Just works perfectly! Thanks again :)

**Comment by DigitalBrainJS** [comment]
Hmm... Sadly, but it doesn't work perfectly :) It seems Edge browser has some bug and this solution doesn't work completely with it. I'm looking for some aditional hack to fix this bug for microsoft's freaky child, but currently i have not 100% working solution...

**Comment by linkurzweg** [comment]
Ah I see. I'm fortunate that I don't have to rely on Microsoft's stupid browsers for my project...
